### PR TITLE
Add drawsBackground parameter for WKWebView

### PR DESCRIPTION
**Pull request by repalash**
Add a drawsBackground parameter in Info.plist, which when set to false allows for a transparent background in `<html>` and `<body>`.

### CODE REVIEW

**Review by jtbandes — APPROVED** [review]
Thanks for the contribution! And sorry it took me a while to get around to reviewing this. I was concerned about using an undocumented API for this, but I think as long as it is opt-in, it should be ok. I've added a `setValue:forUndefinedKey:` implementation to try and avoid crashing if the method stops working in the future.

**Comment by repalash** [comment]
Thanks. And for the library. I have been using it on 3dviewer.xyz

There is an issue I have been facing where the process started for quicklook is never quit and you can see it in Activity Monitor taking up memory. It's called Preview extension Web Content. Have you had this kind of issue before?

**Comment by jtbandes** [comment]
Hm, I have not noticed that, but it's possible that macos keeps the extension alive so it can be reused for multiple previews. Is that what you think is happening, or is it creating a new instance for each preview?

**Comment by repalash** [comment]
Its creating a new process each time I open quicklook. Also seems like its created after the quicklook is closed but that could be just a delay and because I was doing it pretty fast. Its even creating multiple processes for the same file

https://github.com/jtbandes/quicklookjs/assets/7613915/06acba44-79bd-4bbb-b4e6-ad13e1ddf440

Also looks like these are never killed, I found them by going through activity monitor after it handn't been restarted for days and found 50+ of these.

**Comment by jtbandes** [comment]
I can reproduce the same behavior on my machine but it looks like they do _eventually_ go away, at least sometimes... I wonder if there is some way to tell WKWebView to tear down the content process after the preview is closed?

**Comment by jtbandes** [comment]
If the OS is keeping PreviewViewController around just in case you preview the same file again, then it might need to be updated to support unloading & reloading the web view each time to avoid this.

**Comment by repalash** [comment]
Yeah I am looking for some way to stop the process. 
But it's creating a new content process for the same file everytime it's opened.
The only thing I found is that we can use process pool for webview.

**Comment by repalash** [comment]
I guess if JavaScript keeps running in the webview we can use that to detect when the user closes the view either by some window load event or resize event.  And then use that to stop the web view in swift.

**Comment by jtbandes** [comment]
I would hope that we can use `viewDidDisappear`, but I have not tried it yet

**Comment by jtbandes** [comment]
Moving discussion to a new issue https://github.com/jtbandes/quicklookjs/issues/7

**Pull request merged**
